# Generated by Django 4.0.6 on 2022-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_email_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='NoName', max_length=40),
        ),
    ]
