# Generated by Django 4.0.6 on 2022-09-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
